laser_filter:
  ros__parameters:
    scan_filter_chain:
      - name: footprint_filter
        type: laser_filters/LaserScanBoxFilter
        params:
          box_frame: base_link
          min_x: -0.09
          max_x:  0.40
          min_y: -0.20
          max_y:  0.20
          min_z: -0.10
          max_z:  0.30
