scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: footprint_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -0.30
        max_x: 0.30
        min_y: -0.25
        max_y: 0.25
        min_z: -0.1
        max_z: 0.3
        invert: false
