# ===============================
# 每个车型一个二级 key，名字与 car_mode 对应
robot_model:
  brushless_senior_diff:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.10115, 0.0, 0.23618, 0.0, 0.0, 0.0]
    base_to_camera: [0.19024, 0.00024, 0.22022, 0.0, 0.0, 0.0]

  flagship_4wd_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.24699, 0.00002, 0.24466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29879, 0.00024, 0.1722, 0.0, 0.0, 0.0]

  flagship_4wd_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.23835, 0.00002, 0.28466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29014, 0.00024, 0.2122, 0.0, 0.0, 0.0]

  flagship_four_wheel_diff_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.24699, 0.00002, 0.24466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29879, 0.00024, 0.1722, 0.0, 0.0, 0.0]

  flagship_four_wheel_diff_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.23835, 0.00002, 0.28466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29014, 0.00024, 0.2122, 0.0, 0.0, 0.0]

  flagship_mec_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.24699, 0.00002, 0.24466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29879, 0.00024, 0.1722, 0.0, 0.0, 0.0]

  flagship_mec_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.23835, 0.00002, 0.28466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29014, 0.00024, 0.2122, 0.0, 0.0, 0.0]

  four_wheel_diff_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.24699, 0.00002, 0.24466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29879, 0.00024, 0.1722, 0.0, 0.0, 0.0]

  four_wheel_diff_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.23835, 0.00002, 0.28466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29014, 0.00024, 0.2122, 0.0, 0.0, 0.0]

  top_mec_EightDrive:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.26583, 0.00018, 0.19506, 0.0, 0.0, 0.0]
    base_to_camera: [0.33962, 0.00005, 0.1697, 0.0, 0.0, 0.0]

  mini_4wd:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.03163, 0.00009, 0.09292, 0.0, 0.0, 0.0]
    base_to_camera: [0.10709, 0.00032, 0.0767, 0.0, 0.0, 0.0]

  mini_akm:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.05134, 0.0, 0.09452, 0.0, 0.0, 0.0]
    base_to_camera: [0.11365, 0.00017, 0.0762, 0.0, 0.0, 0.0]

  mini_diff:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.05134, 0.0, 0.09452, 0.0, 0.0, 0.0]
    base_to_camera: [0.11365, 0.00017, 0.0762, 0.0, 0.0, 0.0]

  mini_mec:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.03163, 0.00009, 0.09502, 0.0, 0.0, 0.0]
    base_to_camera: [0.10709, 0.00032, 0.0762, 0.0, 0.0, 0.0]

  mini_omni:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.015, 0.0, 0.17, 0.0, 0.0, 0.0]
    base_to_camera: [0.075, 0.12, 0.0, 0.0, 0.0, 0.0]

  mini_tank:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.02799, 0.00005, 0.09602, 0.0, 0.0, 0.0]
    base_to_camera: [0.09673, 0.00012, 0.0777, 0.0, 0.0, 0.0]

  S100_diff:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.08874, 0.00067, 0.11102, 0.0, 0.0, 0.0]
    base_to_camera: [0.16578, 0.00095, 0.0897, 0.0, 0.0, 0.0]

  S200_diff:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.08874, 0.00067, 0.11102, 0.0, 0.0, 0.0]
    base_to_camera: [0.16578, 0.00095, 0.1682, 0.0, 0.0, 0.0]

  senior_4wd_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.09113, 0.00067, 0.11102, 0.0, 0.0, 0.0]
    base_to_camera: [0.16083, 0.00075, 0.0897, 0.0, 0.0, 0.0]

  senior_4wd_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.15699, 0.00201, 0.14652, 0.0, 0.0, 0.0]
    base_to_camera: [0.2316, 0.00224, 0.1282, 0.0, 0.0, 0.0]

  senior_akm:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.08874, 0.00067, 0.11102, 0.0, 0.0, 0.0]
    base_to_camera: [0.16578, 0.00095, 0.0897, 0.0, 0.0, 0.0]

  senior_diff:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.05911, 0.00016, 0.13416, 0.0, 0.0, 0.0]
    base_to_camera: [0.16614, 0.00023, 0.1087, 0.0, 0.0, 0.0]

  senior_mec_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.09113, 0.00067, 0.11102, 0.0, 0.0, 0.0]
    base_to_camera: [0.16083, 0.00075, 0.0897, 0.0, 0.0, 0.0]

  senior_mec_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.15699, 0.00002, 0.14652, 0.0, 0.0, 0.0]
    base_to_camera: [0.2316, 0.00025, 0.1282, 0.0, 0.0, 0.0]

  senior_omni:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.06719, 0.0001, 0.12802, 0.0, 0.0, 0.0]
    base_to_camera: [0.15548, 0.00012, 0.1097, 0.0, 0.0, 0.0]

  top_4wd_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.23835, 0.00002, 0.28466, 0.0, 0.0, 0.0]
    base_to_camera: [0.29014, 0.00024, 0.2122, 0.0, 0.0, 0.0]

  top_4wd_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.14499, 0.00002, 0.18652, 0.0, 0.0, 0.0]
    base_to_camera: [0.2286, 0.0003, 0.1682, 0.0, 0.0, 0.0]

  top_akm_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.23979, 0.00017, 0.15302, 0.0, 0.0, 0.0]
    base_to_camera: [0.3124, 0.00004, 0.1347, 0.0, 0.0, 0.0]

  top_akm_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.25033, 0.00182, 0.1504, 0.0, 0.0, 0.0]
    base_to_camera: [0.32039, 0.00164, 0.13208, 0.0, 0.0, 0.0]

  top_mec_bs:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.13865, 0.00002, 0.12652, 0.0, 0.0, 0.0]
    base_to_camera: [0.2089, 0.00025, 0.1082, 0.0, 0.0, 0.0]

  top_mec_dl:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.14499, 0.00002, 0.18652, 0.0, 0.0, 0.0]
    base_to_camera: [0.2286, 0.0003, 0.1682, 0.0, 0.0, 0.0]

  top_omni:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.144, 0.00018, 0.13806, 0.0, 0.0, 0.0]
    base_to_camera: [0.21733, 0.00026, 0.1127, 0.0, 0.0, 0.0]

  V550_4wd:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.03163, 0.00009, 0.09502, 0.0, 0.0, 0.0]
    base_to_camera: [0.10709, 0.00032, 0.0762, 0.0, 0.0, 0.0]

  V550_akm:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.03163, 0.00009, 0.09502, 0.0, 0.0, 0.0]
    base_to_camera: [0.10709, 0.00032, 0.0762, 0.0, 0.0, 0.0]

  V550_mec:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.05134, 0.0, 0.09452, 0.0, 0.0, 0.0]
    base_to_camera: [0.11365, 0.00017, 0.0762, 0.0, 0.0, 0.0]

  #autoware_senior_akm/autoware_s200_single_antenna/autoware_top_akm_single_antenna/
  #autoware_top_akm_dual_antenna/autoware_s200_dual_antenna/
  autoware_senior_akm:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.08874, 0.00067, 0.11102, 0.0, 0.0, 0.0]
    base_to_camera: [0.16578, 0.00095, 0.0897, 0.0, 0.0, 0.0]

  autoware_s200_single_antenna:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.08874, 0.00067, 0.11102, 0.0, 0.0, 0.0]
    base_to_camera: [0.16578, 0.00095, 0.1682, 0.0, 0.0, 0.0]
  autoware_s200_dual_antenna:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.08874, 0.00067, 0.11102, 0.0, 0.0, 0.0]
    base_to_camera: [0.16578, 0.00095, 0.1682, 0.0, 0.0, 0.0]
  autoware_top_akm_single_antenna:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.25033, 0.00182, 0.1504, 0.0, 0.0, 0.0]
    base_to_camera: [0.32039, 0.00164, 0.13208, 0.0, 0.0, 0.0]
  autoware_top_akm_dual_antenna:
    base_to_link: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_gyro: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    base_to_laser:  [0.25033, 0.00182, 0.1504, 0.0, 0.0, 0.0]
    base_to_camera: [0.32039, 0.00164, 0.13208, 0.0, 0.0, 0.0]
