# 可选车型型号 对应填入car_mode
  # mini_mec、mini_akm、mini_tank、mini_4wd、mini_diff、mini_omni
  # V550_mec、V550_4wd、V550_akm
  # senior_akm、top_akm_bs、top_akm_dl
  # senior_mec_bs、senior_mec_dl、top_mec_bs、top_mec_dl、top_mec_EightDrive、flagship_mec_bs、flagship_mec_dl
  # senior_omni、top_omni
  # senior_4wd_bs、senior_4wd_dl、flagship_4wd_bs、flagship_4wd_dl、top_4wd_bs、top_4wd_dl
  # senior_diff、four_wheel_diff_bs、four_wheel_diff_dl、flagship_four_wheel_diff_bs、flagship_four_wheel_diff_dl
  # S100_diff、S200_diff、brushless_senior_diff
  
  #autoware_senior_akm/autoware_s200_single_antenna/autoware_top_akm_single_antenna/
  #autoware_top_akm_dual_antenna/autoware_s200_dual_antenna/


car_mode: senior_akm      

# 底盘超声波避障功能的开启与关闭  false关闭 true开启
# 此项配置仅对有超声波硬件的车型有效
ranger_avoid_flag: false

# 可选雷达型号 对应填入lidar_type
  # ls_M10_uart ls_M10_net ls_M10P_uart ls_M10P_net  
  # ls_N10_uart ls_N10_net ls_N10Plus_uart ls_N10Plus_net  
  # ld14   ld06  ldstl06n  rplidar_c1  
  # lscx

lidar_type: ls_M10P_uart     

# ls_M10/ls_N10系列单线雷达可修改内容
x10:
  lidar_port: /dev/wheeltec_lidar  # 雷达连接串口名称 使用网口请将值改为空
  #de volgende 2 lijnen aangepast RT , omdat ze volledige hoeken wegnemen. Behouden alleen de achterkant.
  #angle_disable_min: [30,120,290]         # 雷达扫描最小裁剪角度 填整数 例：12000 单位: 0.01°
  #angle_disable_max: [70,240,330]        # 雷达扫描最大裁剪角度 填整数 例：24000 单位: 0.01°
  angle_disable_min: [30,120,290]         # 雷达扫描最小裁剪角度 填整数 例：12000 单位: 0.01°
  angle_disable_max: [70,240,330]        # 雷达扫描最大裁剪角度 填整数 例：24000 单位: 0.01°

# lscx系列多线雷达可修改内容
lscx:
  angle_disable_min: [12000]        # 雷达扫描最小裁剪角度 填整数 例：12000 单位: 0.01°
  angle_disable_max: [24000]         # 雷达扫描最大裁剪角度 填整数 例：24000 单位: 0.01°

# 可选imu型号 对应填入imu_mode
  # stm32  H30 

imu_mode: stm32 

# 可选相机型号 对应填入camera_mode
  # astra  astra_pro   dabai_u3   gemini   usb

camera_mode: astra
